// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: browsercontroller.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_browsercontroller_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_browsercontroller_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "utilities.pb.h"
#include "types.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_browsercontroller_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_browsercontroller_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_browsercontroller_2eproto;
namespace osirixgrpc {
class BrowserControllerCopyFilesIfNeededRequest;
struct BrowserControllerCopyFilesIfNeededRequestDefaultTypeInternal;
extern BrowserControllerCopyFilesIfNeededRequestDefaultTypeInternal _BrowserControllerCopyFilesIfNeededRequest_default_instance_;
class BrowserControllerDatabaseSelectionResponse;
struct BrowserControllerDatabaseSelectionResponseDefaultTypeInternal;
extern BrowserControllerDatabaseSelectionResponseDefaultTypeInternal _BrowserControllerDatabaseSelectionResponse_default_instance_;
}  // namespace osirixgrpc
PROTOBUF_NAMESPACE_OPEN
template <>
::osirixgrpc::BrowserControllerCopyFilesIfNeededRequest* Arena::CreateMaybeMessage<::osirixgrpc::BrowserControllerCopyFilesIfNeededRequest>(Arena*);
template <>
::osirixgrpc::BrowserControllerDatabaseSelectionResponse* Arena::CreateMaybeMessage<::osirixgrpc::BrowserControllerDatabaseSelectionResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace osirixgrpc {

// ===================================================================


// -------------------------------------------------------------------

class BrowserControllerDatabaseSelectionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osirixgrpc.BrowserControllerDatabaseSelectionResponse) */ {
 public:
  inline BrowserControllerDatabaseSelectionResponse() : BrowserControllerDatabaseSelectionResponse(nullptr) {}
  ~BrowserControllerDatabaseSelectionResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BrowserControllerDatabaseSelectionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BrowserControllerDatabaseSelectionResponse(const BrowserControllerDatabaseSelectionResponse& from);
  BrowserControllerDatabaseSelectionResponse(BrowserControllerDatabaseSelectionResponse&& from) noexcept
    : BrowserControllerDatabaseSelectionResponse() {
    *this = ::std::move(from);
  }

  inline BrowserControllerDatabaseSelectionResponse& operator=(const BrowserControllerDatabaseSelectionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BrowserControllerDatabaseSelectionResponse& operator=(BrowserControllerDatabaseSelectionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BrowserControllerDatabaseSelectionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BrowserControllerDatabaseSelectionResponse* internal_default_instance() {
    return reinterpret_cast<const BrowserControllerDatabaseSelectionResponse*>(
               &_BrowserControllerDatabaseSelectionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BrowserControllerDatabaseSelectionResponse& a, BrowserControllerDatabaseSelectionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BrowserControllerDatabaseSelectionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BrowserControllerDatabaseSelectionResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BrowserControllerDatabaseSelectionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BrowserControllerDatabaseSelectionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BrowserControllerDatabaseSelectionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BrowserControllerDatabaseSelectionResponse& from) {
    BrowserControllerDatabaseSelectionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BrowserControllerDatabaseSelectionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "osirixgrpc.BrowserControllerDatabaseSelectionResponse";
  }
  protected:
  explicit BrowserControllerDatabaseSelectionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeriesFieldNumber = 2,
    kStudiesFieldNumber = 3,
    kStatusFieldNumber = 1,
  };
  // repeated .osirixgrpc.DicomSeries series = 2;
  int series_size() const;
  private:
  int _internal_series_size() const;

  public:
  void clear_series() ;
  ::osirixgrpc::DicomSeries* mutable_series(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomSeries >*
      mutable_series();
  private:
  const ::osirixgrpc::DicomSeries& _internal_series(int index) const;
  ::osirixgrpc::DicomSeries* _internal_add_series();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomSeries>& _internal_series() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomSeries>* _internal_mutable_series();
  public:
  const ::osirixgrpc::DicomSeries& series(int index) const;
  ::osirixgrpc::DicomSeries* add_series();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomSeries >&
      series() const;
  // repeated .osirixgrpc.DicomStudy studies = 3;
  int studies_size() const;
  private:
  int _internal_studies_size() const;

  public:
  void clear_studies() ;
  ::osirixgrpc::DicomStudy* mutable_studies(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomStudy >*
      mutable_studies();
  private:
  const ::osirixgrpc::DicomStudy& _internal_studies(int index) const;
  ::osirixgrpc::DicomStudy* _internal_add_studies();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomStudy>& _internal_studies() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomStudy>* _internal_mutable_studies();
  public:
  const ::osirixgrpc::DicomStudy& studies(int index) const;
  ::osirixgrpc::DicomStudy* add_studies();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomStudy >&
      studies() const;
  // .osirixgrpc.Status status = 1;
  bool has_status() const;
  void clear_status() ;
  const ::osirixgrpc::Status& status() const;
  PROTOBUF_NODISCARD ::osirixgrpc::Status* release_status();
  ::osirixgrpc::Status* mutable_status();
  void set_allocated_status(::osirixgrpc::Status* status);
  private:
  const ::osirixgrpc::Status& _internal_status() const;
  ::osirixgrpc::Status* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::osirixgrpc::Status* status);
  ::osirixgrpc::Status* unsafe_arena_release_status();
  // @@protoc_insertion_point(class_scope:osirixgrpc.BrowserControllerDatabaseSelectionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomSeries > series_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomStudy > studies_;
    ::osirixgrpc::Status* status_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_browsercontroller_2eproto;
};// -------------------------------------------------------------------

class BrowserControllerCopyFilesIfNeededRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest) */ {
 public:
  inline BrowserControllerCopyFilesIfNeededRequest() : BrowserControllerCopyFilesIfNeededRequest(nullptr) {}
  ~BrowserControllerCopyFilesIfNeededRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BrowserControllerCopyFilesIfNeededRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BrowserControllerCopyFilesIfNeededRequest(const BrowserControllerCopyFilesIfNeededRequest& from);
  BrowserControllerCopyFilesIfNeededRequest(BrowserControllerCopyFilesIfNeededRequest&& from) noexcept
    : BrowserControllerCopyFilesIfNeededRequest() {
    *this = ::std::move(from);
  }

  inline BrowserControllerCopyFilesIfNeededRequest& operator=(const BrowserControllerCopyFilesIfNeededRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BrowserControllerCopyFilesIfNeededRequest& operator=(BrowserControllerCopyFilesIfNeededRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BrowserControllerCopyFilesIfNeededRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BrowserControllerCopyFilesIfNeededRequest* internal_default_instance() {
    return reinterpret_cast<const BrowserControllerCopyFilesIfNeededRequest*>(
               &_BrowserControllerCopyFilesIfNeededRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BrowserControllerCopyFilesIfNeededRequest& a, BrowserControllerCopyFilesIfNeededRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BrowserControllerCopyFilesIfNeededRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BrowserControllerCopyFilesIfNeededRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BrowserControllerCopyFilesIfNeededRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BrowserControllerCopyFilesIfNeededRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BrowserControllerCopyFilesIfNeededRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BrowserControllerCopyFilesIfNeededRequest& from) {
    BrowserControllerCopyFilesIfNeededRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BrowserControllerCopyFilesIfNeededRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "osirixgrpc.BrowserControllerCopyFilesIfNeededRequest";
  }
  protected:
  explicit BrowserControllerCopyFilesIfNeededRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathsFieldNumber = 2,
    kBrowserFieldNumber = 1,
  };
  // repeated string paths = 2;
  int paths_size() const;
  private:
  int _internal_paths_size() const;

  public:
  void clear_paths() ;
  const std::string& paths(int index) const;
  std::string* mutable_paths(int index);
  void set_paths(int index, const std::string& value);
  void set_paths(int index, std::string&& value);
  void set_paths(int index, const char* value);
  void set_paths(int index, const char* value, std::size_t size);
  void set_paths(int index, absl::string_view value);
  std::string* add_paths();
  void add_paths(const std::string& value);
  void add_paths(std::string&& value);
  void add_paths(const char* value);
  void add_paths(const char* value, std::size_t size);
  void add_paths(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& paths() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_paths();

  private:
  const std::string& _internal_paths(int index) const;
  std::string* _internal_add_paths();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_paths() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_paths();

  public:
  // .osirixgrpc.BrowserController browser = 1;
  bool has_browser() const;
  void clear_browser() ;
  const ::osirixgrpc::BrowserController& browser() const;
  PROTOBUF_NODISCARD ::osirixgrpc::BrowserController* release_browser();
  ::osirixgrpc::BrowserController* mutable_browser();
  void set_allocated_browser(::osirixgrpc::BrowserController* browser);
  private:
  const ::osirixgrpc::BrowserController& _internal_browser() const;
  ::osirixgrpc::BrowserController* _internal_mutable_browser();
  public:
  void unsafe_arena_set_allocated_browser(
      ::osirixgrpc::BrowserController* browser);
  ::osirixgrpc::BrowserController* unsafe_arena_release_browser();
  // @@protoc_insertion_point(class_scope:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> paths_;
    ::osirixgrpc::BrowserController* browser_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_browsercontroller_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BrowserControllerDatabaseSelectionResponse

// .osirixgrpc.Status status = 1;
inline bool BrowserControllerDatabaseSelectionResponse::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.status_ != nullptr);
  return value;
}
inline const ::osirixgrpc::Status& BrowserControllerDatabaseSelectionResponse::_internal_status() const {
  const ::osirixgrpc::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::osirixgrpc::Status&>(
      ::osirixgrpc::_Status_default_instance_);
}
inline const ::osirixgrpc::Status& BrowserControllerDatabaseSelectionResponse::status() const {
  // @@protoc_insertion_point(field_get:osirixgrpc.BrowserControllerDatabaseSelectionResponse.status)
  return _internal_status();
}
inline void BrowserControllerDatabaseSelectionResponse::unsafe_arena_set_allocated_status(
    ::osirixgrpc::Status* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  if (status) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osirixgrpc.BrowserControllerDatabaseSelectionResponse.status)
}
inline ::osirixgrpc::Status* BrowserControllerDatabaseSelectionResponse::release_status() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::osirixgrpc::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::osirixgrpc::Status* BrowserControllerDatabaseSelectionResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:osirixgrpc.BrowserControllerDatabaseSelectionResponse.status)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::osirixgrpc::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::osirixgrpc::Status* BrowserControllerDatabaseSelectionResponse::_internal_mutable_status() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::osirixgrpc::Status>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::osirixgrpc::Status* BrowserControllerDatabaseSelectionResponse::mutable_status() {
  ::osirixgrpc::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:osirixgrpc.BrowserControllerDatabaseSelectionResponse.status)
  return _msg;
}
inline void BrowserControllerDatabaseSelectionResponse::set_allocated_status(::osirixgrpc::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(status));
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:osirixgrpc.BrowserControllerDatabaseSelectionResponse.status)
}

// repeated .osirixgrpc.DicomSeries series = 2;
inline int BrowserControllerDatabaseSelectionResponse::_internal_series_size() const {
  return _impl_.series_.size();
}
inline int BrowserControllerDatabaseSelectionResponse::series_size() const {
  return _internal_series_size();
}
inline ::osirixgrpc::DicomSeries* BrowserControllerDatabaseSelectionResponse::mutable_series(int index) {
  // @@protoc_insertion_point(field_mutable:osirixgrpc.BrowserControllerDatabaseSelectionResponse.series)
  return _internal_mutable_series()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomSeries >*
BrowserControllerDatabaseSelectionResponse::mutable_series() {
  // @@protoc_insertion_point(field_mutable_list:osirixgrpc.BrowserControllerDatabaseSelectionResponse.series)
  return _internal_mutable_series();
}
inline const ::osirixgrpc::DicomSeries& BrowserControllerDatabaseSelectionResponse::_internal_series(int index) const {
  return _internal_series().Get(index);
}
inline const ::osirixgrpc::DicomSeries& BrowserControllerDatabaseSelectionResponse::series(int index) const {
  // @@protoc_insertion_point(field_get:osirixgrpc.BrowserControllerDatabaseSelectionResponse.series)
  return _internal_series(index);
}
inline ::osirixgrpc::DicomSeries* BrowserControllerDatabaseSelectionResponse::_internal_add_series() {
  return _internal_mutable_series()->Add();
}
inline ::osirixgrpc::DicomSeries* BrowserControllerDatabaseSelectionResponse::add_series() {
  ::osirixgrpc::DicomSeries* _add = _internal_add_series();
  // @@protoc_insertion_point(field_add:osirixgrpc.BrowserControllerDatabaseSelectionResponse.series)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomSeries >&
BrowserControllerDatabaseSelectionResponse::series() const {
  // @@protoc_insertion_point(field_list:osirixgrpc.BrowserControllerDatabaseSelectionResponse.series)
  return _internal_series();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomSeries>&
BrowserControllerDatabaseSelectionResponse::_internal_series() const {
  return _impl_.series_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomSeries>*
BrowserControllerDatabaseSelectionResponse::_internal_mutable_series() {
  return &_impl_.series_;
}

// repeated .osirixgrpc.DicomStudy studies = 3;
inline int BrowserControllerDatabaseSelectionResponse::_internal_studies_size() const {
  return _impl_.studies_.size();
}
inline int BrowserControllerDatabaseSelectionResponse::studies_size() const {
  return _internal_studies_size();
}
inline ::osirixgrpc::DicomStudy* BrowserControllerDatabaseSelectionResponse::mutable_studies(int index) {
  // @@protoc_insertion_point(field_mutable:osirixgrpc.BrowserControllerDatabaseSelectionResponse.studies)
  return _internal_mutable_studies()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomStudy >*
BrowserControllerDatabaseSelectionResponse::mutable_studies() {
  // @@protoc_insertion_point(field_mutable_list:osirixgrpc.BrowserControllerDatabaseSelectionResponse.studies)
  return _internal_mutable_studies();
}
inline const ::osirixgrpc::DicomStudy& BrowserControllerDatabaseSelectionResponse::_internal_studies(int index) const {
  return _internal_studies().Get(index);
}
inline const ::osirixgrpc::DicomStudy& BrowserControllerDatabaseSelectionResponse::studies(int index) const {
  // @@protoc_insertion_point(field_get:osirixgrpc.BrowserControllerDatabaseSelectionResponse.studies)
  return _internal_studies(index);
}
inline ::osirixgrpc::DicomStudy* BrowserControllerDatabaseSelectionResponse::_internal_add_studies() {
  return _internal_mutable_studies()->Add();
}
inline ::osirixgrpc::DicomStudy* BrowserControllerDatabaseSelectionResponse::add_studies() {
  ::osirixgrpc::DicomStudy* _add = _internal_add_studies();
  // @@protoc_insertion_point(field_add:osirixgrpc.BrowserControllerDatabaseSelectionResponse.studies)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osirixgrpc::DicomStudy >&
BrowserControllerDatabaseSelectionResponse::studies() const {
  // @@protoc_insertion_point(field_list:osirixgrpc.BrowserControllerDatabaseSelectionResponse.studies)
  return _internal_studies();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomStudy>&
BrowserControllerDatabaseSelectionResponse::_internal_studies() const {
  return _impl_.studies_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::osirixgrpc::DicomStudy>*
BrowserControllerDatabaseSelectionResponse::_internal_mutable_studies() {
  return &_impl_.studies_;
}

// -------------------------------------------------------------------

// BrowserControllerCopyFilesIfNeededRequest

// .osirixgrpc.BrowserController browser = 1;
inline bool BrowserControllerCopyFilesIfNeededRequest::has_browser() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.browser_ != nullptr);
  return value;
}
inline const ::osirixgrpc::BrowserController& BrowserControllerCopyFilesIfNeededRequest::_internal_browser() const {
  const ::osirixgrpc::BrowserController* p = _impl_.browser_;
  return p != nullptr ? *p : reinterpret_cast<const ::osirixgrpc::BrowserController&>(
      ::osirixgrpc::_BrowserController_default_instance_);
}
inline const ::osirixgrpc::BrowserController& BrowserControllerCopyFilesIfNeededRequest::browser() const {
  // @@protoc_insertion_point(field_get:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.browser)
  return _internal_browser();
}
inline void BrowserControllerCopyFilesIfNeededRequest::unsafe_arena_set_allocated_browser(
    ::osirixgrpc::BrowserController* browser) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.browser_);
  }
  _impl_.browser_ = browser;
  if (browser) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.browser)
}
inline ::osirixgrpc::BrowserController* BrowserControllerCopyFilesIfNeededRequest::release_browser() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::osirixgrpc::BrowserController* temp = _impl_.browser_;
  _impl_.browser_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::osirixgrpc::BrowserController* BrowserControllerCopyFilesIfNeededRequest::unsafe_arena_release_browser() {
  // @@protoc_insertion_point(field_release:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.browser)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::osirixgrpc::BrowserController* temp = _impl_.browser_;
  _impl_.browser_ = nullptr;
  return temp;
}
inline ::osirixgrpc::BrowserController* BrowserControllerCopyFilesIfNeededRequest::_internal_mutable_browser() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.browser_ == nullptr) {
    auto* p = CreateMaybeMessage<::osirixgrpc::BrowserController>(GetArenaForAllocation());
    _impl_.browser_ = p;
  }
  return _impl_.browser_;
}
inline ::osirixgrpc::BrowserController* BrowserControllerCopyFilesIfNeededRequest::mutable_browser() {
  ::osirixgrpc::BrowserController* _msg = _internal_mutable_browser();
  // @@protoc_insertion_point(field_mutable:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.browser)
  return _msg;
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_allocated_browser(::osirixgrpc::BrowserController* browser) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.browser_);
  }
  if (browser) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(browser));
    if (message_arena != submessage_arena) {
      browser = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, browser, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.browser_ = browser;
  // @@protoc_insertion_point(field_set_allocated:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.browser)
}

// repeated string paths = 2;
inline int BrowserControllerCopyFilesIfNeededRequest::_internal_paths_size() const {
  return _impl_.paths_.size();
}
inline int BrowserControllerCopyFilesIfNeededRequest::paths_size() const {
  return _internal_paths_size();
}
inline void BrowserControllerCopyFilesIfNeededRequest::clear_paths() {
  _internal_mutable_paths()->Clear();
}
inline std::string* BrowserControllerCopyFilesIfNeededRequest::add_paths() {
  std::string* _s = _internal_add_paths();
  // @@protoc_insertion_point(field_add_mutable:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
  return _s;
}
inline const std::string& BrowserControllerCopyFilesIfNeededRequest::paths(int index) const {
  // @@protoc_insertion_point(field_get:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
  return _internal_paths(index);
}
inline std::string* BrowserControllerCopyFilesIfNeededRequest::mutable_paths(int index) {
  // @@protoc_insertion_point(field_mutable:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
  return _internal_mutable_paths()->Mutable(index);
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_paths(int index, const std::string& value) {
  _internal_mutable_paths()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_paths(int index, std::string&& value) {
  _internal_mutable_paths()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_paths(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_paths()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_paths(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_paths()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::set_paths(int index, absl::string_view value) {
  _internal_mutable_paths()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::add_paths(const std::string& value) {
  _internal_mutable_paths()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::add_paths(std::string&& value) {
  _internal_mutable_paths()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::add_paths(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_paths()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::add_paths(const char* value, std::size_t size) {
  _internal_mutable_paths()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline void BrowserControllerCopyFilesIfNeededRequest::add_paths(absl::string_view value) {
  _internal_mutable_paths()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
BrowserControllerCopyFilesIfNeededRequest::paths() const {
  // @@protoc_insertion_point(field_list:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
  return _internal_paths();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* BrowserControllerCopyFilesIfNeededRequest::mutable_paths() {
  // @@protoc_insertion_point(field_mutable_list:osirixgrpc.BrowserControllerCopyFilesIfNeededRequest.paths)
  return _internal_mutable_paths();
}
inline const std::string& BrowserControllerCopyFilesIfNeededRequest::_internal_paths(int index) const {
  return _internal_paths().Get(index);
}
inline std::string* BrowserControllerCopyFilesIfNeededRequest::_internal_add_paths() {
  return _internal_mutable_paths()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
BrowserControllerCopyFilesIfNeededRequest::_internal_paths() const {
  return _impl_.paths_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
BrowserControllerCopyFilesIfNeededRequest::_internal_mutable_paths() {
  return &_impl_.paths_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace osirixgrpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_browsercontroller_2eproto_2epb_2eh
