name: Documentation
description: Improve our documentation
title: "Documentation: "
labels: ["documentation"]
projects: ["osirixgrpc/osirixgrpc"]
assignees:
  - mdblackledge
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feedback on our documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: feature-scope
    attributes:
      label: Documentation Scope
      description: |
        Is this documentation change request related to OsiriXgrpc as a whole or to the pyOsiriX as a whole?
      options:
        - OsiriXgrpc
        - pyOsiriX
        - Either/Not Sure
      default: 0
    validations:
      required: true
  - type: input
    id: osirixgrpc-version
    attributes:
      label: OsiriXgrpc Version
      description: What version of OsiriXgrpc are you running?
      placeholder: "0.2.1-dev71"
    validations:
      required: true
  - type: textarea
    id: documentation-suggestion
    attributes:
      label: How could we improve our documentation?
      description: |
        Let us know in as much detail as possible which documentation needs changing and why.
      placeholder: |
        **Page link**
        Provide a link to the documentation page that needs improving.
        
        **Describe the issue with the documentation**
        A clear and concise description of what the documentation issue is.
        
        **Expected improvement**
        A clear and concise description of what you expected to find in the documentation.
        
        **Additional context**
        Add any other context about the documentation issue here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](osirixgrpc.github.io/osirixgrpc/contributing/CODE_OF_CONDUCT.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
