name: Generic
description: A generic issue
title: "Generic issue: "
labels: ["generic"]
projects: ["osirixgrpc/osirixgrpc"]
assignees:
  - mdblackledge
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in OsiriXgrpc!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: feature-scope
    attributes:
      label: Documentation Scope
      description: |
        Is this issue related to OsiriXgrpc as a whole or to the pyOsiriX as a whole?
      options:
        - OsiriXgrpc
        - pyOsiriX
        - Either/Not Sure
      default: 0
    validations:
      required: true
  - type: input
    id: osirixgrpc-version
    attributes:
      label: OsiriXgrpc Version
      description: What version of OsiriXgrpc are you running?
      placeholder: "0.2.1-dev71"
    validations:
      required: true
  - type: textarea
    id: issue-text
    attributes:
      label: What would you like to see?
      description: |
        Let us know in as much detail as possible about your issue.
      placeholder: |
        **Issue description**
        Provide as much detail as possible so that we can assist you.

    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](osirixgrpc.github.io/osirixgrpc/contributing/CODE_OF_CONDUCT.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
