#include "gRPCService.h"
#include "gRPCCache.h"

#define gRPCServiceMessageImplementation(name, requestType, responseType, delegateClass) \
    grpc::Status gRPCService::name(grpc::ServerContext* context, \
                                  const osirixgrpc::requestType* request, \
                                  osirixgrpc::responseType* response ) \
    {\
        \
        dispatch_sync(dispatch_get_main_queue(), ^{[delegateClass name: request: response: _cache];}); \
        return grpc::Status::OK;\
    }

gRPCService::gRPCService(gRPCCache *cache)
{
    _cache = cache;
}

# pragma mark Osirix messages
gRPCServiceMessageImplementation(OsirixCurrentBrowser, Empty, OsirixCurrentBrowserResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixFrontmostViewer, Empty, OsirixFrontmostViewerResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixDisplayed2DViewers, Empty, OsirixDisplayed2DViewersResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixFrontmostVRController, Empty, OsirixFrontmostVRControllerResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixDisplayedVRControllers, Empty, OsirixDisplayedVRControllersResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixVersion, Empty, OsirixVersionResponse, gRPCOsirixDelegate)

# pragma mark cache messages
gRPCServiceMessageImplementation(OsirixCacheUids, Empty, OsirixCacheUidsResponse, gRPCOsirixDelegate)
gRPCServiceMessageImplementation(OsirixCacheObjectForUid, OsirixCacheObjectForUidRequest, OsirixCacheObjectForUidResponse, gRPCOsirixDelegate)

# pragma mark ViewerController messages
gRPCServiceMessageImplementation(ViewerControllerCloseViewer, ViewerController, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerPixList, ViewerControllerPixListRequest, ViewerControllerPixListResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerNeedsDisplayUpdate, ViewerController, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerROIList, ViewerControllerROIListRequest, ViewerControllerROIListResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerNewROI, ViewerControllerNewROIRequest, ViewerControllerNewROIResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerCurDCM, ViewerController, ViewerControllerCurDCMResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerROIsWithName, ViewerControllerROIsWithNameRequest, ViewerControllerROIsWithNameResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerSelectedROIs, ViewerController, ViewerControllerSelectedROIsResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerIsDataVolumic, ViewerControllerIsDataVolumicRequest, ViewerControllerIsDataVolumicResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerCopyViewerWindow, ViewerController, ViewerControllerCopyViewerWindowResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerResampleViewerController, ViewerControllerResampleViewerControllerRequest, ViewerControllerResampleViewerControllerResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerBlendingController, ViewerController, ViewerControllerBlendingControllerResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerVRControllers, ViewerController, ViewerControllerVRControllersResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerTitle, ViewerController, ViewerControllerTitleResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerModality, ViewerController, ViewerControllerModalityResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerMovieIdx, ViewerController, ViewerControllerMovieIdxResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerSetMovieIdx, ViewerControllerSetMovieIdxRequest, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerMaxMovieIdx, ViewerController, ViewerControllerMaxMovieIdxResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerIdx, ViewerController, ViewerControllerIdxResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerSetIdx, ViewerControllerSetIdxRequest, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerDisplayedIdx, ViewerController, ViewerControllerDisplayedIdxResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerSetDisplayedIdx, ViewerControllerSetDisplayedIdxRequest, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerFlippedData, ViewerController, ViewerControllerFlippedDataResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerWLWW, ViewerController, ViewerControllerWLWWResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerSetWLWW, ViewerControllerSetWLWWRequest, Response, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerOpenVRViewerForMode, ViewerControllerOpenVRViewerForModeRequest, ViewerControllerOpenVRViewerForModeResponse, gRPCViewerControllerDelegate)
gRPCServiceMessageImplementation(ViewerControllerFuseWithViewer, ViewerControllerFuseWithViewerRequest, Response, gRPCViewerControllerDelegate)

# pragma mark DCMPix messages
gRPCServiceMessageImplementation(DCMPixConvertToRGB, DCMPixConvertToRGBRequest, Response, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixConvertToBW, DCMPixConvertToBWRequest, Response, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixIsRGB, DCMPix, DCMPixIsRGBResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixComputeROI, DCMPixComputeROIRequest, DCMPixComputeROIResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixROIValues, DCMPixROIValuesRequest, DCMPixROIValuesResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixShape, DCMPix, DCMPixShapeResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixSpacing, DCMPix, DCMPixSpacingResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixOrigin, DCMPix, DCMPixOriginResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixOrientation, DCMPix, DCMPixOrientationResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixSliceLocation, DCMPix, DCMPixSliceLocationResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixSourceFile, DCMPix, DCMPixSourceFileResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixImage, DCMPix, DCMPixImageResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixSetImage, DCMPixSetImageRequest, Response, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixGetMapFromROI, DCMPixGetMapFromROIRequest, DCMPixGetMapFromROIResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixDicomImage, DCMPix, DCMPixDicomImageResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixDicomSeries, DCMPix, DCMPixDicomSeriesResponse, gRPCDCMPixDelegate)
gRPCServiceMessageImplementation(DCMPixDicomStudy, DCMPix, DCMPixDicomStudyResponse, gRPCDCMPixDelegate)

# pragma mark ROI messages
gRPCServiceMessageImplementation(ROIDelete, ROI, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIFlipHorizontally, ROI, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIFlipVertically, ROI, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIArea, ROI, ROIAreaResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROICentroid, ROI, ROICentroidResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIRotate, ROIRotateRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIMove, ROIMoveRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIPix, ROI, ROIPixResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIIType, ROI, ROIITypeResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIName, ROI, ROINameResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROISetName, ROISetNameRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIColor, ROI, ROIColorResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROISetColor, ROISetColorRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIOpacity, ROI, ROIOpacityResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROISetOpacity, ROISetOpacityRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIThickness, ROI, ROIThicknessResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROISetThickness, ROISetThicknessRequest, Response, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROIPoints, ROI, ROIPointsResponse, gRPCROIDelegate)
gRPCServiceMessageImplementation(ROISetPoints, ROISetPointsRequest, Response, gRPCROIDelegate)

# pragma mark VRController messages
gRPCServiceMessageImplementation(VRControllerViewer2D, VRController, VRControllerViewer2DResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerBlendingController, VRController, VRControllerBlendingControllerResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerStyle, VRController, VRControllerStyleResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerTitle, VRController, VRControllerTitleResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerROIVolumes, VRController, VRControllerROIVolumesResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerRenderingMode, VRController, VRControllerRenderingModeResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerSetRenderingMode, VRControllerSetRenderingModeRequest, Response, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerWLWW, VRController, VRControllerWLWWResponse, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerSetWLWW, VRControllerSetWLWWRequest, Response, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerHideROIVolume, VRControllerHideROIVolumeRequest, Response, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerDisplayROIVolume, VRControllerDisplayROIVolumeRequest, Response, gRPCVRControllerDelegate)
gRPCServiceMessageImplementation(VRControllerNeedsDisplayUpdate, VRController, Response, gRPCVRControllerDelegate)

# pragma mark ROIVolume messages
gRPCServiceMessageImplementation(ROIVolumeTexture, ROIVolume, ROIVolumeTextureResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeSetTexture, ROIVolumeSetTextureRequest, Response, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeVolume, ROIVolume, ROIVolumeVolumeResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeColor, ROIVolume, ROIVolumeColorResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeSetColor, ROIVolumeSetColorRequest, Response, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeOpacity, ROIVolume, ROIVolumeOpacityResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeSetOpacity, ROIVolumeSetOpacityRequest, Response, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeFactor, ROIVolume, ROIVolumeFactorResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeSetFactor, ROIVolumeSetFactorRequest, Response, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeVisible, ROIVolume, ROIVolumeVisibleResponse, gRPCROIVolumeDelegate)
gRPCServiceMessageImplementation(ROIVolumeName, ROIVolume, ROIVolumeNameResponse, gRPCROIVolumeDelegate)

# pragma mark BrowserController messages
gRPCServiceMessageImplementation(BrowserControllerDatabaseSelection, BrowserController, BrowserControllerDatabaseSelectionResponse, gRPCBrowserControllerDelegate)
gRPCServiceMessageImplementation(BrowserControllerCopyFilesIfNeeded, BrowserControllerCopyFilesIfNeededRequest, Response, gRPCBrowserControllerDelegate)
gRPCServiceMessageImplementation(BrowserControllerOpenViewerFromImages, BrowserControllerOpenViewerFromImagesRequest, BrowserControllerOpenViewerFromImagesResponse, gRPCBrowserControllerDelegate)
gRPCServiceMessageImplementation(BrowserControllerDatabaseStudies, BrowserController, BrowserControllerDatabaseStudiesResponse, gRPCBrowserControllerDelegate)

# pragma mark DicomImage messages
gRPCServiceMessageImplementation(DicomImageWidth, DicomImage, DicomImageWidthResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageHeight, DicomImage, DicomImageHeightResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageSOPInstanceUID, DicomImage, DicomImageSOPInstanceUIDResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageCompletePath, DicomImage, DicomImageCompletePathResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageDate, DicomImage, DicomImageDateResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageNumberOfFrames, DicomImage, DicomImageNumberOfFramesResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageModality, DicomImage, DicomImageModalityResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageSeries, DicomImage, DicomImageSeriesResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageSliceLocation, DicomImage, DicomImageSliceLocationResponse, gRPCDicomImageDelegate)
gRPCServiceMessageImplementation(DicomImageInstanceNumber, DicomImage, DicomImageInstanceNumberResponse, gRPCDicomImageDelegate)

# pragma mark DicomSeries messages
gRPCServiceMessageImplementation(DicomSeriesPaths, DicomSeries, DicomSeriesPathsResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesPreviousSeries, DicomSeries, DicomSeriesPreviousSeriesResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesNextSeries, DicomSeries, DicomSeriesNextSeriesResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesSortedImages, DicomSeries, DicomSeriesSortedImagesResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesStudy, DicomSeries, DicomSeriesStudyResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesImages, DicomSeries, DicomSeriesImagesResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesSeriesInstanceUID, DicomSeries, DicomSeriesSeriesInstanceUIDResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesSeriesSOPClassUID, DicomSeries, DicomSeriesSeriesSOPClassUIDResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesSeriesDescription, DicomSeries, DicomSeriesSeriesDescriptionResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesModality, DicomSeries, DicomSeriesModalityResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesName, DicomSeries, DicomSeriesNameResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesDate, DicomSeries, DicomSeriesDateResponse, gRPCDicomSeriesDelegate)
gRPCServiceMessageImplementation(DicomSeriesNumberOfImages, DicomSeries, DicomSeriesNumberOfImagesResponse, gRPCDicomSeriesDelegate)

# pragma mark DicomStudy messages
gRPCServiceMessageImplementation(DicomStudyPaths, DicomStudy, DicomStudyPathsResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyImages, DicomStudy, DicomStudyImagesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyModalities, DicomStudy, DicomStudyModalitiesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyNoFiles, DicomStudy, DicomStudyNoFilesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyRawNoFiles, DicomStudy, DicomStudyRawNoFilesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyNumberOfImages, DicomStudy, DicomStudyNumberOfImagesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudySeries, DicomStudy, DicomStudySeriesResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyName, DicomStudy, DicomStudyNameResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyDate, DicomStudy, DicomStudyDateResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyDateAdded, DicomStudy, DicomStudyDateAddedResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyDateOfBirth, DicomStudy, DicomStudyDateOfBirthResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyInstitutionName, DicomStudy, DicomStudyInstitutionNameResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyModality, DicomStudy, DicomStudyModalityResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyPatientID, DicomStudy, DicomStudyPatientIDResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyPatientUID, DicomStudy, DicomStudyPatientUIDResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyPatientSex, DicomStudy, DicomStudyPatientSexResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyPerformingPhysician, DicomStudy, DicomStudyPerformingPhysicianResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyReferringPhysician, DicomStudy, DicomStudyReferringPhysicianResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyStudyInstanceUID, DicomStudy, DicomStudyStudyInstanceUIDResponse, gRPCDicomStudyDelegate)
gRPCServiceMessageImplementation(DicomStudyStudyName, DicomStudy, DicomStudyStudyNameResponse, gRPCDicomStudyDelegate)
