#import "gRPCDelegate.h"
#import "browsercontroller.pb.h"

@interface gRPCBrowserControllerDelegate : NSObject

delegateDeclaration(BrowserControllerDatabaseSelection, BrowserController, BrowserControllerDatabaseSelectionResponse)
delegateDeclaration(BrowserControllerCopyFilesIfNeeded, BrowserControllerCopyFilesIfNeededRequest, Response)
delegateDeclaration(BrowserControllerOpenViewerFromImages, BrowserControllerOpenViewerFromImagesRequest, BrowserControllerOpenViewerFromImagesResponse)
delegateDeclaration(BrowserControllerDatabaseStudies, BrowserController, BrowserControllerDatabaseStudiesResponse)

@end
