name: MkDocs Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: pip install mkdocs-material

      - if: github.ref == 'refs/heads/dev'
        name: Append warning to README if dev
        run: |
          sed -i '/__Welcome__/i Warning: this is for development only\n\n' docs/docs/README.md
    
      - name: Deploy to GitHub Pages
        run: |
          cd docs
          mkdocs gh-deploy --force
