name: MkDocs Build

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build MkDocs
        run: |
          cd docs
          mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
