name: Publish dev to test-PyPI

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade build twine

      - name: Resolve README and LICENSE  # Symlinks don't seem to resolve well pypi build
        run: |
          rm pyosirix/LICENSE.txt pyosirix/README.md
          cp LICENSE.txt pyosirix/LICENSE.txt
          cp docs/docs/pyosirix/README.md pyosirix/README.md

      - name: Build and publish
        run: |
          cd pyosirix
          python3 -m build
          python3 -m twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
